version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/back-end/product # 배포 파일 도착 폴더
    overwrite: yes

permissions:
  - object: /
    pattern: "**" # 모든 파일의 권한 설정
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: script/deploy.sh
      timeout: 60
      runas: root
      #  ValidateService: # deploy-community 의 실행 후, 빌드파일이 배포가 되었다면, 서버체크
      #- location: server-check.sh
      #  timeout: 60
