spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://tripinmyroom-rds.csi3ui1uyurt.ap-northeast-2.rds.amazonaws.com:33060/tripinmyroom
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

amazon:
  s3:
    directoryPath: prod/storyPictures

cloud:
  aws:
    credentials:
      instanceProfile: true

my:
  propereties:
    kakao:
      clientId: ${CLIENT_ID}
      authBaseUrl: ${AUTH_BASE_URL}
      apiBaseUrl: ${API_BASE_URL}
      redirectUrl: ${REDIRECT_URL}
      grantType: "authorization_code"

log_dir: /home/ubuntu/back-end
